### ISSUE TITLE
TensorSpace-Converter YAML configuration

### ISSUE THREAD

**Issue by syt123450** [tensorspace-team/tensorspace-converter#17]
Just a proposal, TensorSpace-Converter load a YAML configuration file and preprocess the model based on YAML configuration.

YAML configuration:
```yaml
input_model_from: tensorflow
input_model_format: tf_keras
output_layer_names:
 - layer1Name
 - layer2Name
 - layer3Name
input_path: ./PATH/TO/MODEL/xxx.h5
output_path: ./PATH/TO/SAVE/DIR
```

Converter shell command:
```bash
tensorspacejs_converter \
  --configuration_yaml=PATH/TO/YAML/FILE/configuration.yaml
```
